name: Tryvi Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Scanning
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy vulnerability scanner with rootfs command
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'rootfs'
        scan-ref: '.'
        severity: 'CRITICAL'

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
