name: Tryvi Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Scanning
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scanners: 'fs,rootfs,repo,vuln,secret,config'
        scan-ref: '.'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
